name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: sh build.sh
    - name: upload
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ceph-dist
        path: ceph-rdma.tar.gz
